export const CONFIG = {
  BASE_ENEMY_SPEED: 200,
  TAP_MARGIN: 60,
  INITIAL_LIFE: 5,
  MAX_LIFE: 5,
  MAX_COMBO_MULTIPLIER: 3.0,
  COUNTDOWN_INTERVAL: 800,
  LAYER_FADE_IN_MS: 500,
  LAYER_FADE_OUT_MS: 2000,
  INTERSTITIAL_INTERVAL: 3,
  REPLAY_BUFFER_FRAMES: 900,
  SKILL_CHOICE_COUNT: 3,
  MAX_ENEMIES_ON_SCREEN: 20,
} as const;
